# Generated by Django 4.2 on 2023-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
