# Generated by Django 4.2 on 2023-06-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_question_test_lecture_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.test'),
        ),
    ]
