# Generated by Django 4.2 on 2023-06-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_lecture_test_test_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lecture'),
        ),
    ]
