"""
Django settings for course_core project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3$sde-sklv81e-=3-dzq#l%(19+xjc4un8e-3vwxwk)tw!4b(p"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["10.0.12.84","0.0.0.0","crm29507.dzencode.net","127.0.0.1"]
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = [
#     'https://crm29507.dzencode.net',
#     # ... другие доверенные домены ...
# ]
CSRF_TRUSTED_ORIGINS = ['https://crm29507.dzencode.net']
# Application definition
import dj_database_url

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "course",
    "django_filters",
    "sorl.thumbnail",
    "allauth",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "course_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "course.context_processor.context"
            ],
        },
    },
]

WSGI_APPLICATION = "course_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# db_from_env = dj_database_url.config(conn_max_age=500)
# DATABASES["default"].update(db_from_env)
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
LOGOUT_REDIRECT_URL = "course:home-page"
LOGIN_REDIRECT_URL = "course:login"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "course.User"


STRIPE_PUBLIC_KEY = "pk_test_51MRyslKDczZ74E9aOuP5Ip76DHi7o3xUaQPltR0CKteHO6KUMg92NOqf4DF3Y6NGTj7zOZW9uQKtMjvTsrz6LAmH00l9m3RgdA"
STRIPE_SECRET_KEY = "sk_test_51MRyslKDczZ74E9anUtqmZvN3bUubk1NPoiHb1twZq2EtHyt4SZM2L8T9ZvPwdDOlnA6GbKdNlfskBbI0iUOCL0i00DP5Gi0yg"
# STRIPE_ENDPOINT_SECRET = "whsec_fdkX5DzbibVVuR0xO0M5TunVh0nLiU56"
STRIPE_ENDPOINT_SECRET = "whsec_d37f7dd461760acc5b615a412f3b082d40299c04c9d9eedcb7edb101bafbb531"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_S3_ACCESS_KEY_ID = "AKIAV4JQALWVQKILIRNG"
AWS_S3_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "s3-django-images"
AWS_S3_REGION_NAME = "eu-central-1"
AWS_QUERYSTRING_AUTH = False


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SOCIALACCOUNT_LOGIN_ON_GET = True
SITE_ID = 1
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}
CLIENT_ID = "174504429263-82ehr5ef0ruo7ja7ophnjvpe83om1jkl.apps.googleusercontent.com"
SECRET_KEY_GOOGLE = "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"
YOUR_DOMAIN = "https://crm29507.dzencode.net/"